language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew

install: ./gradlew setupCIWorkspace
script: ./gradlew build

env:
  global:
    TERM=dumb

notifications:
  email: false
  irc:
    channels:
      - "irc.esper.net#surferconor425"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
      - "Commit message: %{commit_message}"
      - "lol it worked, gg."
